### ISSUE TITLE
Project Goals

### ISSUE THREAD

**Issue by s0kil** [manaphp/manaphp#1]
What are the project goals? In other words, What makes Mana different from other PHP frameworks?

**Comment by manaphp** [comment]
lightweight、productive、easy of use!

**Comment by klesun** [comment]
From what I read in the README, if I get it right, the main cool thing is that it uses coroutines to handle HTTP requests like in nodejs instead of how Apache starts and kills the php script on each request. That's actually the reason we stopped using php in my company: we needed to persist a connection to external service between requests to avoid repeated DNS lookup latency. Wish we'd known about this lib back then...

**Comment by manaphp** [comment]
> From what I read in the README, if I get it right, the main cool thing is that it uses coroutines to handle HTTP requests like in nodejs instead of how Apache starts and kills the php script on each request. That's actually the reason we stopped using php in my company: we needed to persist a connection to external service between requests to avoid repeated DNS lookup latency. Wish we'd known about this lib back then...

we can write a code one time, but it can run in php_mod, fpm, swoole shared memory,swoole coroutine,... mode.

it's five-star features are context management method and connection pool manager and debugger,,and .....


https://github.com/manaphp/manaphp/blob/master/ManaPHP/Component.php#L128

https://github.com/manaphp/manaphp/blob/master/ManaPHP/Data/Redis.php#L241

**Comment by manaphp** [comment]
do not need to study swoole,

**Comment by manaphp** [comment]
https://github.com/manaphp/app-admin is a demo

**Comment by manaphp** [comment]
my work flow is developing in fpm mode but production running in swoole coroutine mode.
we can get easy developing and hight performance!
